# Site settings
title: Stephenluck Tugade
description: 'a blog'
url: 'http://stwebuser.github.io'
baseurl: '/stwebuser.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'stwebuser.github.io'
  email: stwebuser@stwebuser.com
  twitter_username: stwebuser
  facebook_username: stwebuser
  github_username:  stwebuser
  linkedin_username:  stwebuser

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
